events {
    worker_connections 1024;
}

http {
    upstream work{
        server worker0X:5678;
        server worker1X:5678;
        server worker2X:5678;
        server worker3X:5678;
    }

    server {
        listen 80;
        location /Trabalho {
            proxy_pass http://work;
        }
    }
}